name: Android Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Run spotless
        run: ./gradlew spotlessApply

      - name: Create config.json in raw folder
        run: |
          mkdir -p app/src/main/res/raw
          echo '{
            "access_token": "your_access_token_here"
          }' > app/src/main/res/raw/config.json

      - name: Execute unit tests
        run: ./gradlew test --stacktrace

      - name: Generate test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_tests_report.html
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Build app
        run: ./gradlew assembleDebug